version: "3.8"

services:
  notification-server:
    image: golang:1.21-alpine
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app/services/notification-server
    env_file:
      - ./services/notification-server/config/.env
    command: go run main.go

  notification-processor-consumer:
    image: golang:1.21-alpine
    deploy:
      replicas: 2
    volumes:
      - .:/app
    working_dir: /app/services/notification-processor-consumer
    env_file:
      - ./services/notification-processor-consumer/config/.env
    command: go run main.go

  notification-save-result-consumer:
    image: golang:1.21-alpine
    deploy:
      replicas: 2
    volumes:
      - .:/app
    working_dir: /app/services/notification-save-result-consumer
    env_file:
      - ./services/notification-save-result-consumer/config/.env
    command: go run main.go
